name: Node.js CI

on:
  push:
    branches: [ "teste" ]
  pull_request:
    branches: [ "teste" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: npm ci

    - name: Set permissions for Mocha
      run: chmod +x node_modules/.bin/mocha
    - name: Run Rest tests
      run: npm run test-rest
    - name: Run GraphQL tests
      run: npm run test-graphql

    - name: Subir a API Rest 
      run: npm run start &

    - name: Subir a API GraphQL 
      run: npm run start-graphql &

    - name: Esperar as APIs estarem Funcionando
      run: sleep 8